version: '2'
services:
  dbsoan:
    image: postgres:13
    platform: linux/amd64
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./backups:/backups

  odoofleet14:
    image: odoo:14
    platform: linux/amd64
    user: root
    depends_on:
      - dbsoan
    ports:
      - "5085:8069"
      - "20114:8072"
    tty: true
    command: --
    environment:
      - HOST=dbsoan
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
